import type { IconConfig } from 'types/IconConfig';

const IconConfigs: Record<string, IconConfig> = {
	react: {
		iconName: 'FaReact',
		iconLibrary: 'fa',
		color: '#61dafb',
		displayLabel: 'React',
	},
	node: {
		iconName: 'FaNodeJs',
		iconLibrary: 'fa',
		color: '#3c873a',
		displayLabel: 'Node.js',
	},
	javascript: {
		iconName: 'FaJs',
		iconLibrary: 'fa',
		color: '#f7df1e',
		displayLabel: 'JavaScript',
	},
	typescript: {
		iconName: 'SiTypescript',
		iconLibrary: 'si',
		color: '#3178c6',
		displayLabel: 'TypeScript',
	},
	angular: {
		iconName: 'FaAngular',
		iconLibrary: 'fa',
		color: '#dd0031',
		displayLabel: 'Angular',
	},
	python: {
		iconName: 'SiPython',
		iconLibrary: 'si',
		color: '#3776ab',
		displayLabel: 'Python',
	},
	nextjs: {
		iconName: 'SiNextdotjs',
		iconLibrary: 'si',
		color: '#000000',
		displayLabel: 'Next.js',
	},
	docker: {
		iconName: 'SiDocker',
		iconLibrary: 'si',
		color: '#2496ed',
		displayLabel: 'Docker',
	},
	redux: {
		iconName: 'SiRedux',
		iconLibrary: 'si',
		color: '#764abc',
		displayLabel: 'Redux',
	},
	tailwind: {
		iconName: 'SiTailwindcss',
		iconLibrary: 'si',
		color: '#38bdf8',
		displayLabel: 'Tailwind CSS',
	},
	'material-ui': {
		iconName: 'SiMui',
		iconLibrary: 'si',
		color: '#007fff',
		displayLabel: 'Material UI',
	},
	jest: {
		iconName: 'SiJest',
		iconLibrary: 'si',
		color: '#007fff',
		displayLabel: 'Jest',
	},
	'automated-testing': {
		iconName: 'SiJest',
		iconLibrary: 'si',
		color: '#c21325',
		displayLabel: 'Automated Testing',
	},
	csharp: {
		iconName: 'SiSharp',
		iconLibrary: 'si',
		color: '#239120',
		displayLabel: 'C#',
	},
	dotnet: {
		iconName: 'SiDotnet',
		iconLibrary: 'si',
		color: '#512bd4',
		displayLabel: '.NET',
	},
	'azure-devops': {
		iconName: 'Azure DevOps',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-DevOps.svg',
		displayLabel: 'Azure DevOps',
	},
	'azure-openai': {
		iconName: 'Azure OpenAI',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-OpenAI.svg',
		displayLabel: 'Azure OpenAI',
	},
	openai: {
		iconName: 'Azure OpenAI',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-OpenAI.svg',
		displayLabel: 'OpenAI',
	},
	'azure-document-intelligence': {
		iconName: 'Cognitive Services',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Cognitive-Services.svg',
		displayLabel: 'Azure Document Intelligence',
	},
	'azure-functions': {
		iconName: 'Function Apps',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Function-Apps.svg',
		displayLabel: 'Azure Functions',
	},
	'azure-ai-search': {
		iconName: 'Cognitive Search',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Cognitive-Search.svg',
		displayLabel: 'Azure AI Search',
	},
	'vector-db': {
		iconName: 'FaDatabase',
		iconLibrary: 'fa',
		color: '#4db33d',
		displayLabel: 'Vector DB',
	},
	'gpt-4': {
		iconName: 'SiOpenai',
		iconLibrary: 'si',
		color: '#412991',
		displayLabel: 'GPT-4',
	},
	'semantic-kernel': {
		iconName: 'FaBrain',
		iconLibrary: 'fa',
		color: '#512bd4',
		displayLabel: 'Semantic Kernel',
	},
	'ai-agents': {
		iconName: 'SiRobotframework',
		iconLibrary: 'si',
		color: '#000000',
		displayLabel: 'AI Agents',
	},
	linkedin: {
		iconName: 'SiLinkedin',
		iconLibrary: 'si',
		color: '#0077b5',
		displayLabel: 'LinkedIn',
	},
	pubsub: {
		iconName: 'SiApachekafka',
		svgPath: '/azure_icons/Azure-Event-Hubs.svg',
		iconLibrary: 'svg',
		color: '#231f20',
		displayLabel: 'Azure Event Hub',
	},
	'redux-saga': {
		iconName: 'SiReduxsaga',
		iconLibrary: 'si',
		color: '#999999',
		displayLabel: 'Redux-Saga',
	},
	'rest-apis': {
		iconName: 'SiPostman',
		iconLibrary: 'si',
		color: '#ff6c37',
		displayLabel: 'REST APIs',
	},
	agile: {
		iconName: 'SiJira',
		iconLibrary: 'si',
		color: '#0052cc',
		displayLabel: 'Agile',
	},
	seo: {
		iconName: 'SiGoogleoptimize',
		iconLibrary: 'si',
		color: '#4285f4',
		displayLabel: 'SEO',
	},
	strip: {
		iconName: 'SiStripe',
		iconLibrary: 'si',
		color: '#635bff',
		displayLabel: 'Stripe',
	},
	wordpress: {
		iconName: 'SiWordpress',
		iconLibrary: 'si',
		color: '#21759b',
		displayLabel: 'WordPress',
	},
	'google-workspace': {
		iconName: 'SiGoogle',
		iconLibrary: 'si',
		color: '#4285f4',
		displayLabel: 'Google Workspace',
	},
	networking: {
		iconName: 'SiCisco',
		iconLibrary: 'si',
		color: '#1ba0d7',
		displayLabel: 'Networking',
	},
	azure: {
		iconName: 'Azure',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/AI-Studio.svg',
		displayLabel: 'Azure',
	},
	cosmosdb: {
		iconName: 'Cosmos DB',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-Cosmos-DB.svg',
		displayLabel: 'Cosmos DB',
	},
	sql: {
		iconName: 'SQL Server',
		iconLibrary: 'svg',
		color: '#CC2927',
		svgPath: '/azure_icons/Cognitive-Services.svg',
		displayLabel: 'SQL Server',
	},
	devops: {
		iconName: 'Azure DevOps',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-DevOps.svg',
		displayLabel: 'DevOps',
	},
	sass: {
		iconName: 'SiSass',
		iconLibrary: 'si',
		color: '#cc6699',
		displayLabel: 'Sass',
	},
	'react-hook-form': {
		iconName: 'SiReacthookform',
		iconLibrary: 'si',
		color: '#00d8ff',
		displayLabel: 'React Hook Form',
	},
	'azure-static-web-app': {
		iconName: 'Azure Static Web Apps',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-Static-Web-Apps.svg',
		displayLabel: 'Azure Static Web Apps',
	},
	github: {
		iconName: 'SiGithub',
		iconLibrary: 'si',
		color: '#181717',
		displayLabel: 'GitHub',
	},
	mui: {
		iconName: 'SiMui',
		iconLibrary: 'si',
		color: '#0078d4',
		displayLabel: 'MUI',
	},
	yup: {
		iconName: 'FaRandom',
		iconLibrary: 'fa',
		color: '#FFFCV2',
		displayLabel: 'Yup',
	},
	'redux-sagas': {
		iconName: 'SiReduxsaga',
		iconLibrary: 'si',
		color: '#999999',
		displayLabel: 'Redux-Saga',
	},
	storybook: {
		iconName: 'SiStorybook',
		iconLibrary: 'si',
		color: '#FF4785',
		displayLabel: 'Storybook',
	},
	webpack: {
		iconName: 'SiWebpack',
		iconLibrary: 'si',
		color: '#8DD6F9',
		displayLabel: 'Webpack',
	},
	'react-router': {
		iconName: 'SiReactrouter',
		iconLibrary: 'si',
		color: '#CA4245',
		displayLabel: 'React Router',
	},
	html: {
		iconName: 'SiHtml5',
		iconLibrary: 'si',
		color: '#E34F26',
		displayLabel: 'HTML5',
	},
	css: {
		iconName: 'SiCss3',
		iconLibrary: 'si',
		color: '#1572B6',
		displayLabel: 'CSS3',
	},
	'api-management': {
		iconName: 'API Management',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/API-Management.svg',
		displayLabel: 'API Management',
	},
	'application-gateway': {
		iconName: 'Application Gateways',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Application-Gateways.svg',
		displayLabel: 'Application Gateway',
	},
	'github-auth': {
		iconName: 'SiGithub',
		iconLibrary: 'si',
		color: '#181717',
		displayLabel: 'GitHub',
	},
	msal: {
		iconName: 'FaLock',
		iconLibrary: 'fa',
		color: '#0078d4',
		displayLabel: 'MSAL',
	},
	'azure-blob-storage': {
		iconName: 'Azure Blob Storage',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Storage-Azure-Files.svg',
		displayLabel: 'Azure Blob Storage',
	},
	'react-query': {
		iconName: 'SiReactquery',
		iconLibrary: 'si',
		color: '#FF4154',
		displayLabel: 'React Query',
	},
	zustand: {
		iconName: 'SiZustand',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/icons/zustand.svg',
		displayLabel: 'Zustand',
	},
	zod: {
		iconName: 'SiZod',
		iconLibrary: 'si',
		color: '#2C3E50',
		displayLabel: 'Zod',
	},
	'azure-storage-queues': {
		iconName: 'Azure Storage Queue',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-Storage-Queue.svg',
		displayLabel: 'Azure Storage Queues',
	},
	'azure-app-service': {
		iconName: 'Azure App Service',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-App-Services.svg',
		displayLabel: 'Azure App Service',
	},
	'azure-copilot-studio': {
		iconName: 'Azure Copilot Studio',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-Copilot-Studio.svg',
		displayLabel: 'Azure Copilot Studio',
	},
	sharepoint: {
		iconName: 'SharePoint',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/sharepoint.png',
		displayLabel: 'SharePoint',
	},
	axios: {
		iconName: 'SiAxios',
		iconLibrary: 'si',
		color: '#5A29E4',
		displayLabel: 'Axios',
	},
	vite: {
		iconName: 'SiVite',
		iconLibrary: 'si',
		color: '#646CFF',
		displayLabel: 'Vite',
	},
	postgresdb: {
		iconName: 'SiPostgresql',
		iconLibrary: 'si',
		color: '#336791',
		displayLabel: 'PostgreSQL',
	},
	websocket: {
		iconName: 'SiWebsocket',
		iconLibrary: 'si',
		color: '#4DB33D',
		displayLabel: 'WebSocket',
	},
	'azure-event-hub': {
		iconName: 'Azure Event Hub',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-Event-Hubs.svg',
		displayLabel: 'Azure Event Hub',
	},
	'power-platform': {
		iconName: 'Power Platform',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/PowerPlatform.svg',
		displayLabel: 'Power Platform',
	},
	'power-automate': {
		iconName: 'Power Automate',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/PowerAutomate.svg',
		displayLabel: 'Power Automate',
	},
	dataverse: {
		iconName: 'Dataverse',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Dataverse.svg',
		displayLabel: 'Dataverse',
	},
	'power-apps': {
		iconName: 'Power Apps',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/PowerApps.svg',
		displayLabel: 'Power Apps',
	},
	agents: {
		iconName: 'SiRobotframework',
		iconLibrary: 'si',
		color: '#000000',
		displayLabel: 'Agents',
	},
	'github-copilot': {
		iconName: 'GitHub Copilot',
		iconLibrary: 'svg',
		color: '#181717',
		svgPath: '/icons/github-copilot.svg',
		displayLabel: 'GitHub Copilot',
	},
	powershell: {
		iconName: 'PowerShell',
		iconLibrary: 'svg',
		color: '#181717',
		svgPath: '/icons/PowerShell.svg',
		displayLabel: 'PowerShell',
	},
	automation: {
		iconName: 'FaCogs', // Changed from SiAutomation to FaCogs
		iconLibrary: 'fa',
		color: '#F7931E',
		displayLabel: 'Automation',
	},
	scripting: {
		iconName: 'FaCode', // Changed from SiScripting to FaCode
		iconLibrary: 'fa',
		color: '#F7931E',
		displayLabel: 'Scripting',
	},
	git: {
		iconName: 'SiGit',
		iconLibrary: 'si',
		color: '#F05032',
		displayLabel: 'Git',
	},
	'plugin-system': {
		iconName: 'FaPlug', // Changed from SiPlugin to FaPlug for a plug-like icon
		iconLibrary: 'fa',
		color: '#F7931E',
		displayLabel: 'Plugin System',
	},
	'azure-key-vaults': {
		iconName: 'Azure Key Vault',
		iconLibrary: 'svg',
		color: '#0078d4',
		svgPath: '/azure_icons/Azure-Key-Vaults.svg',
		displayLabel: 'Azure Key Vaults',
	},
	ai: {
		iconName: 'SiOpenai',
		iconLibrary: 'si',
		color: '#412991',
		displayLabel: 'AI',
	},
};

export function getIconConfig(name: string): IconConfig | undefined {
	const key = name.toLowerCase().replace(/\s|\./g, '');
	return IconConfigs[key];
}

export function getColor(name: string): string | undefined {
	const config = getIconConfig(name);
	return config?.color;
}
